# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-01 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('sname', models.CharField(max_length=50)),
                ('sloc', models.CharField(max_length=50)),
                ('sfee', models.IntegerField()),
            ],
        ),
    ]
